Daemon
GlanceFromTheScreen/Daemon-Linux pull request #4
Opened 2023-10-23 09:14 UTC by GlanceFromTheScreen

2023-10-27 23:11 UTC, DariaWelt requested changes
Весь код должен лежать в папке lab1.
Лишних файлов не должно быть.
Демон не защищен от повторного запуска.
пид файл должен лежать в /var/run
Не меняется рабочая директория

2023-10-27 23:11 UTC, DariaWelt commented on daemon_executable
Бинарников в репозитории быть не должно

2023-10-27 23:11 UTC, DariaWelt commented on daemon.cpp
> +#include "daemon.h"
тут явно много лишних инклудов. оставьте только нужные, пожалуйста

2023-10-27 23:11 UTC, DariaWelt commented on daemon.cpp
> +    if (pid < 0) {exit(0);}  // exit child process if it wasn't created
В обоих случаях возвращается одинаковый код(успешный), хотя первый случай является ошибкой

2023-11-01 15:52 UTC, GlanceFromTheScreen commented on daemon_executable
убрал

2023-11-01 15:52 UTC, GlanceFromTheScreen commented on daemon.cpp
> +#include "daemon.h"
оставил только необходимые

2023-11-01 15:52 UTC, GlanceFromTheScreen commented on daemon.cpp
> +    if (pid < 0) {exit(0);}  // exit child process if it wasn't created
исправил

2023-11-01 15:57 UTC, GlanceFromTheScreen commented
Перенес файлы в lab1. 
Лишние файлы убрал.
Была ошибка с защитой демона от повторного запуска: цикл демона обновлялся с частотой 30 секунд, и если сигнал приходил на 10-й секунде, то следующие 20 секунд существовало два демона. Проблему исправил. 
Pid-файл перенес в нужную директорию. 
Сделал так, что меняется рабочая директория.

2023-11-05 09:58 UTC, DariaWelt approved these changes
Работа зачтена.

2023-11-05 09:58 UTC, merged