Lab2
GlanceFromTheScreen/Daemon-Linux pull request #5
Opened 2023-11-27 21:47 UTC by GlanceFromTheScreen

2023-11-30 19:46 UTC, DariaWelt requested changes
Уберите std многопоточность

2023-11-30 19:46 UTC, DariaWelt commented on lab2/host/host.cpp
> +    SEG s;
Не понятно зачем создаются все типы взаимодействия, а потом используется только 1 из них. Зачем остальные?

2023-11-30 19:46 UTC, DariaWelt commented on lab2/host/host.cpp
> +        std::future<std::string> future = std::async(std::launch::async, getAnswer);
std многопоточностью пользоваться нельзя, используйте pthread

2023-11-30 19:46 UTC, DariaWelt commented on lab2/host/host.cpp
> +        log.open("log.file");
Мной был показан примерный вариант реализации ввода-вывода в консоль. Тут странные названия файлов myfile.txt и log.file. И зачем открывать файл и сразу закрывать?

2023-12-04 12:48 UTC, GlanceFromTheScreen commented on lab2/host/host.cpp
> +    SEG s;
Согласен, было неразумно. Исправил.

2023-12-04 13:40 UTC, GlanceFromTheScreen commented on lab2/host/host.cpp
> +        log.open("log.file");
Названия изменил на логичные. Насчет открытий и закрытий. Мне нужно быть уверенным, что файл очищен и при этом открывать файл на запись. Поэтому я сначала использую .open (очищаю и информирую о том, что мы в терминале клиента), а потом открываю этот файл на добавление в конец через флаг std::ios::app. Может быть это немного костыльно, но это работает

2023-12-04 13:41 UTC, GlanceFromTheScreen commented
Не убирал std многопоточность пока что. Если положительных моментов лабораторной хватает на 4-5 из 10, то я бы очень хотел на этом и остановиться.

2023-12-09 12:13 UTC, DariaWelt approved these changes
Работа зачтена

2023-12-09 12:13 UTC, merged