Hlamkin_Evgeniy_Lab3
GlanceFromTheScreen/Daemon-Linux pull request #6
Opened 2023-12-21 23:50 UTC by GlanceFromTheScreen

2023-12-22 19:49 UTC, DariaWelt requested changes
Работа будет зачтена после удаления лишнего

2023-12-22 19:49 UTC, DariaWelt commented on lab3/results.txt
Этот файл нужно удалить

2023-12-22 19:49 UTC, DariaWelt commented on lab3/build.sh
> +./prog
билд скрипт не должен запускать код. Только собрать его

2023-12-23 06:20 UTC, GlanceFromTheScreen commented on lab3/results.txt
удалил

2023-12-23 06:20 UTC, GlanceFromTheScreen commented on lab3/build.sh
> +./prog
исправил

2023-12-23 15:53 UTC, DariaWelt approved these changes

2023-12-23 15:53 UTC, merged